### ISSUE TITLE
Bug: Checkbox control does not work with boolean data type/Create new record fails silently

### ISSUE THREAD

**Issue by michaelgfalk** [tomitrescak/mpce#9]
I have a form DetailView with a checkbox element that is bound to a boolean column:
![image](https://user-images.githubusercontent.com/35712723/60485932-ad43ff00-9ce1-11e9-9979-bd5b69707ea8.png)
This Detail view opens correctly if the value of 'certain' is NULL:
![image](https://user-images.githubusercontent.com/35712723/60486086-d19fdb80-9ce1-11e9-82a2-1a4b57ae289d.png)
![image](https://user-images.githubusercontent.com/35712723/60486122-db294380-9ce1-11e9-9bb5-c35a20a2806b.png)
But if 'corporate_entity' is True or False, then the Detail View will not open:
![image](https://user-images.githubusercontent.com/35712723/60486195-eed4aa00-9ce1-11e9-8b56-e4b336976035.png)
![image](https://user-images.githubusercontent.com/35712723/60486242-fac06c00-9ce1-11e9-871c-a1e497789170.png)

The 'save' button on this detail form also fails to work, so long as the checkbox control is present.

**Comment by tomitrescak** [comment]
FIXED. The issue was that MySql was returning the Bit field as "Buffer", that is array of values. Now only a boolean value is returned.

ALSO: The "Silent" fail was due to the fact that you have defined and "Empty" required field. In this case nothing was shown as the error did not belong to any visual field.
